export default {
  panels: [
    {
      index: 0,
      name: 1,
      height: 40,
      width: 60,
      paperHeader: 0,
      paperFooter: 113.385_826_771_653_56,
      printElements: [
        {
          options: {
            left: 5,
            top: 4.5,
            height: 104,
            width: 162,
            right: 163.25,
            bottom: 106,
            vCenter: 82.75,
            hCenter: 54.5,
            coordinateSync: false,
            widthHeightSync: false,
          },
          printElementType: {
            title: '矩形',
            type: 'rect',
          },
        },
        {
          options: {
            left: 1.5,
            top: 7.5,
            height: 9.5,
            width: 168,
            right: 179.25,
            bottom: 20.25,
            vCenter: 95.25,
            hCenter: 13.5,
            title: '重庆市渝中区疾病预防控制中心',
            coordinateSync: false,
            widthHeightSync: false,
            fontSize: 6.75,
            fontWeight: 'bold',
            textAlign: 'center',
            textContentVerticalAlign: 'middle',
            zIndex: 2,
            qrCodeLevel: 0,
          },
          printElementType: {
            type: 'text',
          },
        },
        {
          options: {
            left: 5,
            top: 19.5,
            height: 9,
            width: 162,
            borderWidth: '0.75',
            coordinateSync: false,
            widthHeightSync: false,
            zIndex: 2,
            right: 168.243_736_267_089_84,
            bottom: 26.493_747_711_181_64,
            vCenter: 87.243_736_267_089_84,
            hCenter: 21.993_747_711_181_64,
          },
          printElementType: {
            title: '横线',
            type: 'hline',
          },
        },
        {
          options: {
            left: 4.5,
            top: 24,
            height: 9.75,
            width: 162,
            title: '资产编号',
            field: 'number',
            testData: 'TY2012000021',
            qid: 'number',
            coordinateSync: false,
            widthHeightSync: false,
            zIndex: 2,
            contentPaddingLeft: 3,
            contentPaddingRight: 3,
            qrCodeLevel: 0,
            right: 161.25,
            bottom: 31.5,
            vCenter: 83.25,
            hCenter: 26.625,
            fontSize: 6.75,
            fontWeight: 'bold',
          },
          printElementType: {
            type: 'text',
          },
        },
        {
          options: {
            left: 5,
            top: 36,
            height: 9,
            width: 162,
            borderWidth: '0.75',
            coordinateSync: false,
            widthHeightSync: false,
            zIndex: 2,
            right: 168.75,
            bottom: 40.5,
            vCenter: 87.75,
            hCenter: 36,
          },
          printElementType: {
            title: '横线',
            type: 'hline',
          },
        },
        {
          options: {
            left: 4.5,
            top: 40.5,
            height: 9.75,
            width: 162,
            title: '资产名称',
            field: 'name',
            testData: '办公桌',
            qid: 'name',
            coordinateSync: false,
            widthHeightSync: false,
            zIndex: 2,
            contentPaddingLeft: 3,
            contentPaddingRight: 3,
            qrCodeLevel: 0,
            right: 126,
            bottom: 46.5,
            vCenter: 66,
            hCenter: 41.625,
            fontSize: 6.75,
            fontWeight: 'bold',
          },
          printElementType: {
            type: 'text',
          },
        },
        {
          options: {
            left: 5,
            top: 54,
            height: 9,
            width: 162,
            borderWidth: '0.75',
            coordinateSync: false,
            widthHeightSync: false,
            zIndex: 2,
            right: 167.499_023_437_5,
            bottom: 54.999_023_437_5,
            vCenter: 86.499_023_437_5,
            hCenter: 50.499_023_437_5,
          },
          printElementType: {
            title: '横线',
            type: 'hline',
          },
        },
        {
          options: {
            left: 115.5,
            top: 54,
            height: 54.3,
            width: 9,
            coordinateSync: false,
            widthHeightSync: false,
            zIndex: 2,
            right: 124.5,
            bottom: 108.55,
            vCenter: 120,
            hCenter: 80.9,
          },
          printElementType: {
            title: '竖线',
            type: 'vline',
          },
        },
        {
          options: {
            left: 118.5,
            top: 58.5,
            height: 45,
            width: 45,
            title: '二维码',
            qrcodeType: 'qrcode',
            testData: 'qrcode',
            field: 'qr',
            qid: 'qr',
            qrCodeLevel: 0,
            coordinateSync: false,
            widthHeightSync: false,
            hideTitle: true,
            right: 165,
            bottom: 101.25,
            vCenter: 142.5,
            hCenter: 78.75,
          },
          printElementType: {
            type: 'qrcode',
          },
        },
        {
          options: {
            left: 4.5,
            top: 58.5,
            height: 9.75,
            width: 111,
            title: '存放地点',
            field: 'addr',
            testData: '903',
            qid: 'addr',
            coordinateSync: false,
            widthHeightSync: false,
            zIndex: 2,
            contentPaddingLeft: 3,
            contentPaddingRight: 2.25,
            qrCodeLevel: 0,
            right: 126.75,
            bottom: 66,
            vCenter: 66.75,
            hCenter: 61.125,
            fontSize: 6.75,
            fontWeight: 'bold',
          },
          printElementType: {
            type: 'text',
          },
        },
        {
          options: {
            left: 5,
            top: 72,
            height: 9,
            width: 111.5,
            borderWidth: '0.75',
            coordinateSync: false,
            widthHeightSync: false,
            zIndex: 2,
            right: 120,
            bottom: 78.75,
            vCenter: 66,
            hCenter: 74.25,
          },
          printElementType: {
            title: '横线',
            type: 'hline',
          },
        },
        {
          options: {
            left: 4.5,
            top: 76.5,
            height: 9.75,
            width: 111,
            title: '使用部门',
            field: 'user_dept',
            testData: '财务科',
            qid: 'user_dept',
            coordinateSync: false,
            widthHeightSync: false,
            zIndex: 2,
            contentPaddingLeft: 3,
            contentPaddingRight: 2.25,
            qrCodeLevel: 0,
            right: 108,
            bottom: 85.5,
            vCenter: 56.25,
            hCenter: 80.625,
            fontSize: 6.75,
            fontWeight: 'bold',
          },
          printElementType: {
            type: 'text',
          },
        },
        {
          options: {
            left: 5,
            top: 90,
            height: 9,
            width: 111.5,
            borderWidth: '0.75',
            coordinateSync: false,
            widthHeightSync: false,
            zIndex: 2,
            right: 108.999_023_437_5,
            bottom: 94.749_023_437_5,
            vCenter: 63.999_023_437_5,
            hCenter: 90.249_023_437_5,
          },
          printElementType: {
            title: '横线',
            type: 'hline',
          },
        },
        {
          options: {
            left: 4.5,
            top: 94.5,
            height: 9.75,
            width: 111,
            title: '负&nbsp;&nbsp;责&nbsp;人',
            field: 'user_name',
            testData: '小明',
            qid: 'user_name',
            right: 99.75,
            bottom: 101.25,
            vCenter: 53.25,
            hCenter: 96.375,
            coordinateSync: false,
            widthHeightSync: false,
            zIndex: 2,
            contentPaddingLeft: 3,
            contentPaddingRight: 2.25,
            qrCodeLevel: 0,
            fontSize: 6.75,
            fontWeight: 'bold',
          },
          printElementType: {
            type: 'text',
          },
        },
      ],
      paperNumberLeft: 0,
      paperNumberTop: 0,
      paperNumberDisabled: true,
      paperNumberContinue: true,
      watermarkOptions: {},
      panelLayoutOptions: {},
    },
  ],
};
